In [1]:
from expert2 import *
import wrinkle2
import util
import cv2
import matplotlib.pyplot as plt

class Dagger:
    frame_id = 0
    def __init__(self):
        import time
        path = "./"+time.strftime("%m%d-%H%M")
        if os.path.exists(path):
            shutil.rmtree(path)
        os.mkdir(path)

        self.tt_expert_pos = np.array([])
        self.tt_pred_pos = np.array([])
        self.tt_handles = np.array([])
        self.tt_feat = np.array([])
        self.tt_log = np.array([])
        self.path = path
        pass

    def update(self,handles, pred_pos, expert_pos, feat, log):
        handles = np.array(handles).ravel();
        expert_pos = np.array(expert_pos).ravel()
        pred_pos = np.array(pred_pos).ravel()
        

        self.tt_pred_pos = np.vstack((self.tt_pred_pos,pred_pos)) if self.tt_pred_pos.size else pred_pos
        self.tt_feat = np.vstack((self.tt_feat,feat)) if self.tt_feat.size else feat
        self.tt_handles = np.vstack((self.tt_handles, handles)) if self.tt_handles.size else handles
        self.tt_expert_pos = np.vstack((self.tt_expert_pos, expert_pos)) if self.tt_expert_pos.size else expert_pos
        self.tt_log = np.vstack((self.tt_log, this_log)) if self.tt_log.size else this_log
        
        np.savez(self.path+'/data',tt_expert_pos = self.tt_expert_pos,
                 tt_pred_pos = self.tt_pred_pos, tt_feat = self.tt_feat, 
                 tt_handles = self.tt_handles, tt_log = self.tt_log)
        pass
    
    def frame_path(self):
        self.frame_id = self.frame_id + 1
        return self.path+"/%04i"%(self.frame_id-1)
    
    def saved_frame_path(self):
        return self.path+"/%04i"%(self.frame_id-1)+'.png'
    
    
    
def random_hands(x):
    hands=np.zeros((2,3))
    # pick two random positions for hands, which have at most x (won't break the cloth)
    while True:
        # random from [0,0,0] [x,0,0], which is the first two handles
        hands[0] = [random.uniform(-x/4,x/4),random.uniform(-x/4,x/4),random.uniform(-x/4,x/4)]
        hands[1] = [random.uniform(-x/4,x/4)+x,random.uniform(-x/4,x/4),random.uniform(-x/4,x/4)]
        if np.linalg.norm(np.subtract(hands[0],hands[1])) < x:
            break
    
    return hands
    
    
remesh_fag = False
render_image = True
render_depth = False
MOVEMENT_THRESH = 1e-5
BETA = 0.95
cloth_x = 1.0 #width of the cloth 
cloth_y = 2.0 #length of the cloth
delta = 0.01 # controller gain, multiplier
nr_frame = 100 # number of frames each setup consists
nr_pass = 30 # number of different passes (setups)

expert = arcsim_expert()
expert.create_sheet(1,5,2,10,"./python_sheet",[0,0,-9.81],[0,0,0],0,0,remesh_fag)
expert.setup("./python_sheet/sheet.json")
expert_controller = expert.expert_flat #expert type

# initialize the positions
handles=[[0,0,0],[cloth_x,0,0],[0,cloth_y,0],[cloth_x,cloth_y,0]]
# frame_id
dagger = Dagger()

for p in range(nr_pass):
    hands = random_hands(x=cloth_x)
    pos = np.zeros((2,3))    
    BETA_p = BETA**p
    # start each run
    for i in range(nr_frame):
        # handles
        handles_prev = handles
        expert.advance()
        handles = expert.apply_hand(handles, hands, delta)
        handles = expert.apply_expert(handles, pos, delta)
        expert.set_handle(handles)
        # save images
        expert.save_frame(dagger.frame_path(), render_image, render_depth)
        print dagger.saved_frame_path()
        # get the visual feature
        im = cv2.imread(dagger.saved_frame_path())
        feat = wrinkle2.xhist(im)
        expert_pos = np.array(expert_controller(handles,cloth_x,cloth_y))
        if p>0:
            pred_pos = rt.feat_to_act(feat=feat.reshape(1,-1))
        else:
            pred_pos = np.zeros(expert_pos.shape)
        expert.advance()
        
        # apply the robot controllers positions
        if random.random()>BETA_p:
            use_pred = 1
            pos = pred_pos
        else:
            use_pred = 0
            pos = expert_pos        

        this_log = np.array([p,i,use_pred]);
        dagger.update(log=this_log, handles=handles_prev, pred_pos=pred_pos, expert_pos=expert_pos, feat=feat)
        
        # determine whether to terminate the run
        d = np.array(handles_prev).ravel() - np.array(handles).ravel()
        d = sum(d*d)
        if d<MOVEMENT_THRESH:
            break;
        
    # begin training
    from rfdic import random_trees
    num_class = 10
    rt = random_trees(tt_handles=dagger.tt_handles, 
                      tt_pos=dagger.tt_expert_pos, 
                      tt_feat=dagger.tt_feat, 
                      num_class=num_class, 
                      num_trees=10)

./1116-2001/0000.png


/home/rmqlife/anaconda2/lib/python2.7/site-packages/skimage/feature/_hog.py:119: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15
  'be changed to `L2-Hys` in v0.15', skimage_deprecation)


./1116-2001/0001.png
./1116-2001/0002.png
./1116-2001/0003.png
./1116-2001/0004.png
./1116-2001/0005.png
./1116-2001/0006.png
./1116-2001/0007.png
./1116-2001/0008.png
./1116-2001/0009.png
./1116-2001/0010.png
./1116-2001/0011.png
./1116-2001/0012.png
./1116-2001/0013.png
./1116-2001/0014.png
./1116-2001/0015.png
./1116-2001/0016.png
./1116-2001/0017.png
./1116-2001/0018.png
./1116-2001/0019.png
./1116-2001/0020.png
./1116-2001/0021.png
./1116-2001/0022.png
./1116-2001/0023.png
./1116-2001/0024.png
./1116-2001/0025.png
./1116-2001/0026.png
./1116-2001/0027.png
./1116-2001/0028.png
./1116-2001/0029.png
./1116-2001/0030.png
./1116-2001/0031.png
./1116-2001/0032.png
./1116-2001/0033.png
./1116-2001/0034.png
./1116-2001/0035.png
./1116-2001/0036.png
./1116-2001/0037.png
./1116-2001/0038.png
./1116-2001/0039.png
./1116-2001/0040.png
./1116-2001/0041.png
./1116-2001/0042.png
./1116-2001/0043.png
./1116-2001/0044.png
./1116-2001/0045.png
./1116-2001/0046.png
./1116-2001/0047.png
./1116-2001/0

IOError: POVRay rendering failed with the following error: povray: cannot open the user configuration file /home/rmqlife/.povray/3.7/povray.conf: No such file or directory
Persistence of Vision(tm) Ray Tracer Version 3.7.0.unofficial (g++ 5.2.1 @
 x86_64-pc-linux-gnu)
This is an unofficial version compiled by:
 Martin Pitt <martin.pitt@ubuntu.com> for Debian <www.debian.org>
 The POV-Ray Team is not responsible for supporting this version.

POV-Ray is based on DKBTrace 2.12 by David K. Buck & Aaron A. Collins
Copyright 1991-2013 Persistence of Vision Raytracer Pty. Ltd.

Primary POV-Ray 3.7 Architects/Developers: (Alphabetically)
  Chris Cason         Thorsten Froehlich  Christoph Lipka   

With Assistance From: (Alphabetically)
  Nicolas Calimet     Jerome Grimbert     James Holsenback    Christoph Hormann 
  Nathan Kopp         Juha Nieminen     

Past Contributors: (Alphabetically)
  Steve Anger         Eric Barish         Dieter Bayer        David K. Buck     
  Nicolas Calimet     Chris Cason         Aaron A. Collins    Chris Dailey      
  Steve Demlow        Andreas Dilger      Alexander Enzmann   Dan Farmer        
  Thorsten Froehlich  Mark Gordon         James Holsenback    Christoph Hormann 
  Mike Hough          Chris Huff          Kari Kivisalo       Nathan Kopp       
  Lutz Kretzschmar    Christoph Lipka     Jochen Lippert      Pascal Massimino  
  Jim McElhiney       Douglas Muir        Juha Nieminen       Ron Parker        
  Bill Pulver         Eduard Schwan       Wlodzimierz Skiba   Robert Skinner    
  Yvo Smellenbergh    Zsolt Szalavari     Scott Taylor        Massimo Valentini 
  Timothy Wegner      Drew Wells          Chris Young       

Other contributors are listed in the documentation.

Support libraries used by POV-Ray:
  ZLib 1.2.8, Copyright 1995-2012 Jean-loup Gailly and Mark Adler
  LibPNG 1.2.54, Copyright 1998-2012 Glenn Randers-Pehrson
  LibJPEG 80, Copyright 1991-2013 Thomas G. Lane, Guido Vollbeding
  LibTIFF 4.0.6, Copyright 1988-1997 Sam Leffler, 1991-1997 SGI
  Boost 1.58, http://www.boost.org/
  OpenEXR, Copyright (c) 2004-2007, Industrial Light & Magic.

Parser Options
  Input file: __temp__.pov
  Remove bounds........On 
  Split unions.........Off
  Library paths:
    /usr/share/povray-3.7
    /usr/share/povray-3.7/ini
    /usr/share/povray-3.7/include
  Clock value:    0.000  (Animation off)
Image Output Options
  Image resolution.....1024 by 768 (rows 1 to 768, columns 1 to 1024).
  Output file.........../1116-2001/0056.png, 24 bpp PNG
  Dithering............Off
  Graphic display......On  (gamma: sRGB)
  Mosaic preview.......Off
  Continued trace......Off
Information Output Options
  All Streams to console..........On 
  Debug Stream to console.........On 
  Fatal Stream to console.........On 
  Render Stream to console........On 
  Statistics Stream to console....On 
  Warning Stream to console.......On 
==== [Parsing...] ==========================================================
Parse Warning: assumed_gamma not specified, so gamma_correction is turned off
 for compatibility with this pre POV-Ray 3.7 scene. See the documentation for
 more details.
Parse Warning: This scene did not contain a #version directive. Please be aware
 that as of POV-Ray 3.7, unless already specified via an INI option, a #version
 is expected as the first declaration in a scene file. POV-Ray may apply
 settings to some features that are intended to maintain compatibility with
 pre-3.7 scenes. You are strongly encouraged to add a #version statement to the
 scene to make your intent clear. Future versions of POV-Ray may make the
 presence of a #version statement mandatory.
----------------------------------------------------------------------------
Parser Statistics
----------------------------------------------------------------------------
Finite Objects:            1
Infinite Objects:          0
Light Sources:             1
Total:                     2
----------------------------------------------------------------------------
Parser Time
  Parse Time:       0 hours  0 minutes  0 seconds (0.001 seconds)
              using 1 thread(s) with 0.000 CPU-seconds total
  Bounding Time:    0 hours  0 minutes  0 seconds (0.000 seconds)
              using 1 thread(s) with 0.000 CPU-seconds total
----------------------------------------------------------------------------
Render Options
  Quality:  9
  Bounding boxes.......On   Bounding threshold: 3
  Antialiasing.........On  (Method 1, Threshold 0.000, Depth 3, Jitter 1.00,
 Gamma 2.50)
==== [Rendering...] ========================================================
Rendered 1024 of 786432 pixels (0%)
Rendered 2048 of 786432 pixels (0%)
Rendered 3072 of 786432 pixels (0%)
Rendered 4096 of 786432 pixels (0%)
Rendered 5120 of 786432 pixels (0%)
Rendered 6144 of 786432 pixels (0%)
Rendered 7168 of 786432 pixels (0%)
Rendered 8192 of 786432 pixels (1%)
Rendered 9216 of 786432 pixels (1%)
Rendered 10240 of 786432 pixels (1%)
Rendered 11264 of 786432 pixels (1%)
Rendered 12288 of 786432 pixels (1%)
Rendered 13312 of 786432 pixels (1%)
Rendered 14336 of 786432 pixels (1%)
Rendered 15360 of 786432 pixels (1%)
Rendered 16384 of 786432 pixels (2%)
Rendered 17408 of 786432 pixels (2%)
Rendered 18432 of 786432 pixels (2%)
Rendered 19456 of 786432 pixels (2%)
Rendered 20480 of 786432 pixels (2%)
Rendered 21504 of 786432 pixels (2%)
Rendered 22528 of 786432 pixels (2%)
Rendered 23552 of 786432 pixels (2%)
Rendered 24576 of 786432 pixels (3%)
Rendered 25600 of 786432 pixels (3%)
Rendered 26624 of 786432 pixels (3%)
Rendered 27648 of 786432 pixels (3%)
Rendered 28672 of 786432 pixels (3%)
Rendered 29696 of 786432 pixels (3%)
Rendered 30720 of 786432 pixels (3%)
Rendered 31744 of 786432 pixels (4%)
Rendered 32768 of 786432 pixels (4%)
Rendered 33792 of 786432 pixels (4%)
Rendered 34816 of 786432 pixels (4%)
Rendered 35840 of 786432 pixels (4%)
Rendered 36864 of 786432 pixels (4%)
Rendered 37888 of 786432 pixels (4%)
Rendered 38912 of 786432 pixels (4%)
Rendered 39936 of 786432 pixels (5%)
Rendered 40960 of 786432 pixels (5%)
Rendered 41984 of 786432 pixels (5%)
Rendered 43008 of 786432 pixels (5%)
Rendered 44032 of 786432 pixels (5%)
Rendered 45056 of 786432 pixels (5%)
Rendered 46080 of 786432 pixels (5%)
Rendered 47104 of 786432 pixels (5%)
Rendered 48128 of 786432 pixels (6%)
Rendered 49152 of 786432 pixels (6%)
Rendered 50176 of 786432 pixels (6%)
Rendered 51200 of 786432 pixels (6%)
Rendered 52224 of 786432 pixels (6%)
Rendered 53248 of 786432 pixels (6%)
Rendered 54272 of 786432 pixels (6%)
Rendered 55296 of 786432 pixels (7%)
Rendered 56320 of 786432 pixels (7%)
Rendered 57344 of 786432 pixels (7%)
Rendered 58368 of 786432 pixels (7%)
Rendered 59392 of 786432 pixels (7%)
Rendered 60416 of 786432 pixels (7%)
Rendered 61440 of 786432 pixels (7%)
Rendered 62464 of 786432 pixels (7%)
Rendered 63488 of 786432 pixels (8%)
Rendered 64512 of 786432 pixels (8%)
Rendered 65536 of 786432 pixels (8%)
Rendered 66560 of 786432 pixels (8%)
Rendered 67584 of 786432 pixels (8%)
Rendered 68608 of 786432 pixels (8%)
Rendered 69632 of 786432 pixels (8%)
Rendered 70656 of 786432 pixels (8%)
Rendered 71680 of 786432 pixels (9%)
Rendered 72704 of 786432 pixels (9%)
Rendered 73728 of 786432 pixels (9%)
Rendered 74752 of 786432 pixels (9%)
Rendered 75776 of 786432 pixels (9%)
Rendered 76800 of 786432 pixels (9%)
Rendered 77824 of 786432 pixels (9%)
Rendered 78848 of 786432 pixels (10%)
Rendered 79872 of 786432 pixels (10%)
Rendered 80896 of 786432 pixels (10%)
Rendered 81920 of 786432 pixels (10%)
Rendered 82944 of 786432 pixels (10%)
Rendered 83968 of 786432 pixels (10%)
Rendered 84992 of 786432 pixels (10%)
Rendered 86016 of 786432 pixels (10%)
Rendered 87040 of 786432 pixels (11%)
Rendered 88064 of 786432 pixels (11%)
Rendered 89088 of 786432 pixels (11%)
Rendered 90112 of 786432 pixels (11%)
Rendered 91136 of 786432 pixels (11%)
Rendered 92160 of 786432 pixels (11%)
Rendered 93184 of 786432 pixels (11%)
Rendered 94208 of 786432 pixels (11%)
Rendered 95232 of 786432 pixels (12%)
Rendered 96256 of 786432 pixels (12%)
Rendered 97280 of 786432 pixels (12%)
Rendered 98304 of 786432 pixels (12%)
Rendered 99328 of 786432 pixels (12%)
Rendered 100352 of 786432 pixels (12%)
Rendered 101376 of 786432 pixels (12%)
Rendered 102400 of 786432 pixels (13%)
Rendered 103424 of 786432 pixels (13%)
Rendered 104448 of 786432 pixels (13%)
Rendered 105472 of 786432 pixels (13%)
Rendered 106496 of 786432 pixels (13%)
Rendered 107520 of 786432 pixels (13%)
Rendered 108544 of 786432 pixels (13%)
Rendered 109568 of 786432 pixels (13%)
Rendered 110592 of 786432 pixels (14%)
Rendered 111616 of 786432 pixels (14%)
Rendered 112640 of 786432 pixels (14%)
Rendered 113664 of 786432 pixels (14%)
Rendered 114688 of 786432 pixels (14%)
Rendered 115712 of 786432 pixels (14%)
Rendered 116736 of 786432 pixels (14%)
Rendered 117760 of 786432 pixels (14%)
Rendered 118784 of 786432 pixels (15%)
Rendered 119808 of 786432 pixels (15%)
Rendered 120832 of 786432 pixels (15%)
Rendered 121856 of 786432 pixels (15%)
Rendered 122880 of 786432 pixels (15%)
Rendered 123904 of 786432 pixels (15%)
Rendered 124928 of 786432 pixels (15%)
Rendered 125952 of 786432 pixels (16%)
Rendered 126976 of 786432 pixels (16%)
Rendered 128000 of 786432 pixels (16%)
Rendered 129024 of 786432 pixels (16%)
Rendered 130048 of 786432 pixels (16%)
Rendered 131072 of 786432 pixels (16%)
Rendered 132096 of 786432 pixels (16%)
Rendered 133120 of 786432 pixels (16%)
Rendered 134144 of 786432 pixels (17%)
Rendered 135168 of 786432 pixels (17%)
Rendered 136192 of 786432 pixels (17%)
Rendered 137216 of 786432 pixels (17%)
Rendered 138240 of 786432 pixels (17%)
Rendered 139264 of 786432 pixels (17%)
Rendered 140288 of 786432 pixels (17%)
Rendered 141312 of 786432 pixels (17%)
Rendered 142336 of 786432 pixels (18%)
Rendered 143360 of 786432 pixels (18%)
Rendered 144384 of 786432 pixels (18%)
Rendered 145408 of 786432 pixels (18%)
Rendered 146432 of 786432 pixels (18%)
Rendered 147456 of 786432 pixels (18%)
Rendered 148480 of 786432 pixels (18%)
Rendered 149504 of 786432 pixels (19%)
Rendered 150528 of 786432 pixels (19%)
Rendered 151552 of 786432 pixels (19%)
Rendered 152576 of 786432 pixels (19%)
Rendered 153600 of 786432 pixels (19%)
Rendered 154624 of 786432 pixels (19%)
Rendered 155648 of 786432 pixels (19%)
Rendered 156672 of 786432 pixels (19%)
Rendered 157696 of 786432 pixels (20%)
Rendered 158720 of 786432 pixels (20%)
Rendered 159744 of 786432 pixels (20%)
Rendered 160768 of 786432 pixels (20%)
Rendered 161792 of 786432 pixels (20%)
Rendered 162816 of 786432 pixels (20%)
Rendered 163840 of 786432 pixels (20%)
Rendered 164864 of 786432 pixels (20%)
Rendered 165888 of 786432 pixels (21%)
Rendered 166912 of 786432 pixels (21%)
Rendered 167936 of 786432 pixels (21%)
Rendered 168960 of 786432 pixels (21%)
Rendered 169984 of 786432 pixels (21%)
Rendered 171008 of 786432 pixels (21%)
Rendered 172032 of 786432 pixels (21%)
Rendered 173056 of 786432 pixels (22%)
Rendered 174080 of 786432 pixels (22%)
Rendered 175104 of 786432 pixels (22%)
Rendered 176128 of 786432 pixels (22%)
Rendered 177152 of 786432 pixels (22%)
Rendered 178176 of 786432 pixels (22%)
Rendered 179200 of 786432 pixels (22%)
Rendered 180224 of 786432 pixels (22%)
Rendered 181248 of 786432 pixels (23%)
Rendered 182272 of 786432 pixels (23%)
Rendered 183296 of 786432 pixels (23%)
Rendered 184320 of 786432 pixels (23%)
Rendered 185344 of 786432 pixels (23%)
Rendered 186368 of 786432 pixels (23%)
Rendered 187392 of 786432 pixels (23%)
Rendered 188416 of 786432 pixels (23%)
Rendered 189440 of 786432 pixels (24%)
Rendered 190464 of 786432 pixels (24%)
Rendered 191488 of 786432 pixels (24%)
Rendered 192512 of 786432 pixels (24%)
Rendered 193536 of 786432 pixels (24%)
Rendered 194560 of 786432 pixels (24%)
Rendered 195584 of 786432 pixels (24%)
Rendered 196608 of 786432 pixels (25%)
Rendered 197632 of 786432 pixels (25%)
Rendered 198656 of 786432 pixels (25%)
Rendered 199680 of 786432 pixels (25%)
Rendered 200704 of 786432 pixels (25%)
Rendered 201728 of 786432 pixels (25%)
Rendered 202752 of 786432 pixels (25%)
Rendered 203776 of 786432 pixels (25%)
Rendered 204800 of 786432 pixels (26%)
Rendered 205824 of 786432 pixels (26%)
Rendered 206848 of 786432 pixels (26%)
Rendered 207872 of 786432 pixels (26%)
Rendered 208896 of 786432 pixels (26%)
Rendered 209920 of 786432 pixels (26%)
Rendered 210944 of 786432 pixels (26%)
Rendered 211968 of 786432 pixels (26%)
Rendered 212992 of 786432 pixels (27%)
Rendered 214016 of 786432 pixels (27%)
Rendered 215040 of 786432 pixels (27%)
Rendered 216064 of 786432 pixels (27%)
Rendered 217088 of 786432 pixels (27%)
Rendered 218112 of 786432 pixels (27%)
Rendered 219136 of 786432 pixels (27%)
Rendered 220160 of 786432 pixels (27%)
Rendered 221184 of 786432 pixels (28%)
Rendered 222208 of 786432 pixels (28%)
Rendered 223232 of 786432 pixels (28%)
Rendered 224256 of 786432 pixels (28%)
Rendered 225280 of 786432 pixels (28%)
Rendered 226304 of 786432 pixels (28%)
Rendered 227328 of 786432 pixels (28%)
Rendered 228352 of 786432 pixels (29%)
Rendered 229376 of 786432 pixels (29%)
Rendered 230400 of 786432 pixels (29%)
Rendered 231424 of 786432 pixels (29%)
Rendered 232448 of 786432 pixels (29%)
Rendered 233472 of 786432 pixels (29%)
Rendered 234496 of 786432 pixels (29%)
Rendered 235520 of 786432 pixels (29%)
Rendered 236544 of 786432 pixels (30%)
Rendered 237568 of 786432 pixels (30%)
Rendered 238592 of 786432 pixels (30%)
Rendered 239616 of 786432 pixels (30%)
Rendered 240640 of 786432 pixels (30%)
Rendered 241664 of 786432 pixels (30%)
Rendered 242688 of 786432 pixels (30%)
Rendered 243712 of 786432 pixels (30%)
Rendered 244736 of 786432 pixels (31%)
Rendered 245760 of 786432 pixels (31%)
Rendered 246784 of 786432 pixels (31%)
Rendered 247808 of 786432 pixels (31%)
Rendered 248832 of 786432 pixels (31%)
Rendered 249856 of 786432 pixels (31%)
Rendered 250880 of 786432 pixels (31%)
Rendered 252928 of 786432 pixels (32%)
Rendered 251904 of 786432 pixels (32%)
Rendered 253952 of 786432 pixels (32%)
Rendered 254976 of 786432 pixels (32%)
Rendered 256000 of 786432 pixels (32%)
Rendered 257024 of 786432 pixels (32%)
Rendered 258048 of 786432 pixels (32%)
Rendered 259072 of 786432 pixels (32%)
Rendered 260096 of 786432 pixels (33%)
Rendered 261120 of 786432 pixels (33%)
Rendered 262144 of 786432 pixels (33%)
Rendered 263168 of 786432 pixels (33%)
Rendered 264192 of 786432 pixels (33%)
Rendered 265216 of 786432 pixels (33%)
Rendered 266240 of 786432 pixels (33%)
Rendered 267264 of 786432 pixels (33%)
Rendered 268288 of 786432 pixels (34%)
Rendered 269312 of 786432 pixels (34%)
Rendered 270336 of 786432 pixels (34%)
Rendered 271360 of 786432 pixels (34%)
Rendered 272384 of 786432 pixels (34%)
Rendered 273408 of 786432 pixels (34%)
Rendered 274432 of 786432 pixels (34%)
Rendered 275456 of 786432 pixels (35%)
Rendered 276480 of 786432 pixels (35%)
Rendered 277504 of 786432 pixels (35%)
Rendered 278528 of 786432 pixels (35%)
Rendered 279552 of 786432 pixels (35%)
Rendered 280576 of 786432 pixels (35%)
Rendered 281600 of 786432 pixels (35%)
Rendered 282624 of 786432 pixels (35%)
Rendered 283648 of 786432 pixels (36%)
Rendered 284672 of 786432 pixels (36%)
Rendered 285696 of 786432 pixels (36%)
Rendered 286720 of 786432 pixels (36%)
Rendered 287744 of 786432 pixels (36%)
Rendered 288768 of 786432 pixels (36%)
Rendered 289792 of 786432 pixels (36%)
Rendered 290816 of 786432 pixels (36%)
Rendered 291840 of 786432 pixels (37%)
Rendered 292864 of 786432 pixels (37%)
Rendered 293888 of 786432 pixels (37%)
Rendered 294912 of 786432 pixels (37%)
Rendered 295936 of 786432 pixels (37%)
Rendered 296960 of 786432 pixels (37%)
Rendered 297984 of 786432 pixels (37%)
Rendered 299008 of 786432 pixels (38%)
Rendered 300032 of 786432 pixels (38%)
Rendered 301056 of 786432 pixels (38%)
Rendered 302080 of 786432 pixels (38%)
Rendered 303104 of 786432 pixels (38%)
Rendered 304128 of 786432 pixels (38%)
Rendered 305152 of 786432 pixels (38%)
Rendered 306176 of 786432 pixels (38%)
Rendered 307200 of 786432 pixels (39%)
Rendered 308224 of 786432 pixels (39%)
Rendered 309248 of 786432 pixels (39%)
Rendered 310272 of 786432 pixels (39%)
Rendered 311296 of 786432 pixels (39%)
Rendered 312320 of 786432 pixels (39%)
Rendered 313344 of 786432 pixels (39%)
Rendered 314368 of 786432 pixels (39%)
Rendered 315392 of 786432 pixels (40%)
Rendered 316416 of 786432 pixels (40%)
Rendered 317440 of 786432 pixels (40%)
Rendered 318464 of 786432 pixels (40%)
Rendered 319488 of 786432 pixels (40%)
Rendered 320512 of 786432 pixels (40%)
Rendered 321536 of 786432 pixels (40%)
Rendered 322560 of 786432 pixels (41%)
Rendered 323584 of 786432 pixels (41%)
Rendered 324608 of 786432 pixels (41%)
Rendered 325632 of 786432 pixels (41%)
Rendered 326656 of 786432 pixels (41%)
Rendered 327680 of 786432 pixels (41%)
Rendered 328704 of 786432 pixels (41%)
Rendered 329728 of 786432 pixels (41%)
Rendered 330752 of 786432 pixels (42%)
Rendered 331776 of 786432 pixels (42%)
Rendered 332800 of 786432 pixels (42%)
Rendered 333824 of 786432 pixels (42%)
Rendered 334848 of 786432 pixels (42%)
Rendered 335872 of 786432 pixels (42%)
Rendered 336896 of 786432 pixels (42%)
Rendered 337920 of 786432 pixels (42%)
Rendered 338944 of 786432 pixels (43%)
Rendered 339968 of 786432 pixels (43%)
Rendered 340992 of 786432 pixels (43%)
Rendered 342016 of 786432 pixels (43%)
Rendered 343040 of 786432 pixels (43%)
Rendered 344064 of 786432 pixels (43%)
Rendered 345088 of 786432 pixels (43%)
Rendered 346112 of 786432 pixels (44%)
Rendered 347136 of 786432 pixels (44%)
Rendered 348160 of 786432 pixels (44%)
Rendered 349184 of 786432 pixels (44%)
Rendered 350208 of 786432 pixels (44%)
Rendered 351232 of 786432 pixels (44%)
Rendered 352256 of 786432 pixels (44%)
Rendered 353280 of 786432 pixels (44%)
Rendered 354304 of 786432 pixels (45%)
Rendered 355328 of 786432 pixels (45%)
Rendered 356352 of 786432 pixels (45%)
Rendered 357376 of 786432 pixels (45%)
Rendered 358400 of 786432 pixels (45%)
Rendered 359424 of 786432 pixels (45%)
Rendered 360448 of 786432 pixels (45%)
Rendered 361472 of 786432 pixels (45%)
Rendered 362496 of 786432 pixels (46%)
Rendered 363520 of 786432 pixels (46%)
Rendered 364544 of 786432 pixels (46%)
Rendered 365568 of 786432 pixels (46%)
Rendered 366592 of 786432 pixels (46%)
Rendered 367616 of 786432 pixels (46%)
Rendered 368640 of 786432 pixels (46%)
Rendered 369664 of 786432 pixels (47%)
Rendered 370688 of 786432 pixels (47%)
Rendered 371712 of 786432 pixels (47%)
Rendered 372736 of 786432 pixels (47%)
Rendered 373760 of 786432 pixels (47%)
Rendered 374784 of 786432 pixels (47%)
Rendered 375808 of 786432 pixels (47%)
Rendered 376832 of 786432 pixels (47%)
Rendered 377856 of 786432 pixels (48%)
Rendered 378880 of 786432 pixels (48%)
Rendered 379904 of 786432 pixels (48%)
Rendered 380928 of 786432 pixels (48%)
Rendered 381952 of 786432 pixels (48%)
Rendered 382976 of 786432 pixels (48%)
Rendered 384000 of 786432 pixels (48%)
Rendered 385024 of 786432 pixels (48%)
Rendered 386048 of 786432 pixels (49%)
Rendered 387072 of 786432 pixels (49%)
Rendered 388096 of 786432 pixels (49%)
Rendered 389120 of 786432 pixels (49%)
Rendered 390144 of 786432 pixels (49%)
Rendered 391168 of 786432 pixels (49%)
Rendered 392192 of 786432 pixels (49%)
Rendered 393216 of 786432 pixels (50%)
Rendered 394240 of 786432 pixels (50%)
Rendered 395264 of 786432 pixels (50%)
Rendered 396288 of 786432 pixels (50%)
Rendered 397312 of 786432 pixels (50%)
Rendered 398336 of 786432 pixels (50%)
Rendered 399360 of 786432 pixels (50%)
Rendered 400384 of 786432 pixels (50%)
Rendered 401408 of 786432 pixels (51%)
Rendered 402432 of 786432 pixels (51%)
Rendered 403456 of 786432 pixels (51%)
Rendered 404480 of 786432 pixels (51%)
Rendered 405504 of 786432 pixels (51%)
Rendered 406528 of 786432 pixels (51%)
Rendered 407552 of 786432 pixels (51%)
Rendered 408576 of 786432 pixels (51%)
Rendered 409600 of 786432 pixels (52%)
Rendered 410624 of 786432 pixels (52%)
Rendered 411648 of 786432 pixels (52%)
Rendered 412672 of 786432 pixels (52%)
Rendered 413696 of 786432 pixels (52%)
Rendered 414720 of 786432 pixels (52%)
Rendered 415744 of 786432 pixels (52%)
Rendered 416768 of 786432 pixels (52%)
Rendered 417792 of 786432 pixels (53%)
Rendered 418816 of 786432 pixels (53%)
Rendered 419840 of 786432 pixels (53%)
Rendered 420864 of 786432 pixels (53%)
Rendered 421888 of 786432 pixels (53%)
Rendered 422912 of 786432 pixels (53%)
Rendered 423936 of 786432 pixels (53%)
Rendered 424960 of 786432 pixels (54%)
Rendered 425984 of 786432 pixels (54%)
Rendered 427008 of 786432 pixels (54%)
Rendered 428032 of 786432 pixels (54%)
Rendered 429056 of 786432 pixels (54%)
Rendered 430080 of 786432 pixels (54%)
Rendered 431104 of 786432 pixels (54%)
Rendered 432128 of 786432 pixels (54%)
Rendered 433152 of 786432 pixels (55%)
Rendered 434176 of 786432 pixels (55%)
Rendered 435200 of 786432 pixels (55%)
Rendered 436224 of 786432 pixels (55%)
Rendered 437248 of 786432 pixels (55%)
Rendered 438272 of 786432 pixels (55%)
Rendered 439296 of 786432 pixels (55%)
Rendered 440320 of 786432 pixels (55%)
Rendered 441344 of 786432 pixels (56%)
Rendered 442368 of 786432 pixels (56%)
Rendered 443392 of 786432 pixels (56%)
Rendered 444416 of 786432 pixels (56%)
Rendered 445440 of 786432 pixels (56%)
Rendered 446464 of 786432 pixels (56%)
Rendered 447488 of 786432 pixels (56%)
Rendered 448512 of 786432 pixels (57%)
Rendered 449536 of 786432 pixels (57%)
Rendered 450560 of 786432 pixels (57%)
Rendered 451584 of 786432 pixels (57%)
Rendered 452608 of 786432 pixels (57%)
Rendered 453632 of 786432 pixels (57%)
Rendered 454656 of 786432 pixels (57%)
Rendered 455680 of 786432 pixels (57%)
Rendered 456704 of 786432 pixels (58%)
Rendered 457728 of 786432 pixels (58%)
Rendered 458752 of 786432 pixels (58%)
Rendered 459776 of 786432 pixels (58%)
Rendered 460800 of 786432 pixels (58%)
Rendered 461824 of 786432 pixels (58%)
Rendered 462848 of 786432 pixels (58%)
Rendered 463872 of 786432 pixels (58%)
Rendered 464896 of 786432 pixels (59%)
Rendered 465920 of 786432 pixels (59%)
Rendered 466944 of 786432 pixels (59%)
Rendered 467968 of 786432 pixels (59%)
Rendered 468992 of 786432 pixels (59%)
Rendered 470016 of 786432 pixels (59%)
Rendered 471040 of 786432 pixels (59%)
Rendered 472064 of 786432 pixels (60%)
Rendered 473088 of 786432 pixels (60%)
Rendered 474112 of 786432 pixels (60%)
Rendered 475136 of 786432 pixels (60%)
Rendered 476160 of 786432 pixels (60%)
Rendered 477184 of 786432 pixels (60%)
Rendered 478208 of 786432 pixels (60%)
Rendered 479232 of 786432 pixels (60%)
Rendered 480256 of 786432 pixels (61%)
Rendered 481280 of 786432 pixels (61%)
Rendered 482304 of 786432 pixels (61%)
Rendered 483328 of 786432 pixels (61%)
Rendered 484352 of 786432 pixels (61%)
Rendered 485376 of 786432 pixels (61%)
Rendered 486400 of 786432 pixels (61%)
Rendered 487424 of 786432 pixels (61%)
Rendered 488448 of 786432 pixels (62%)
Rendered 489472 of 786432 pixels (62%)
Rendered 490496 of 786432 pixels (62%)
Rendered 491520 of 786432 pixels (62%)
Rendered 492544 of 786432 pixels (62%)
Rendered 493568 of 786432 pixels (62%)
Rendered 494592 of 786432 pixels (62%)
Rendered 495616 of 786432 pixels (63%)
Rendered 496640 of 786432 pixels (63%)
Rendered 497664 of 786432 pixels (63%)
Rendered 498688 of 786432 pixels (63%)
Rendered 499712 of 786432 pixels (63%)
Rendered 500736 of 786432 pixels (63%)
Rendered 501760 of 786432 pixels (63%)
Rendered 502784 of 786432 pixels (63%)
Rendered 503808 of 786432 pixels (64%)
Rendered 504832 of 786432 pixels (64%)
Rendered 505856 of 786432 pixels (64%)
Rendered 506880 of 786432 pixels (64%)
Rendered 507904 of 786432 pixels (64%)
Rendered 508928 of 786432 pixels (64%)
Rendered 509952 of 786432 pixels (64%)
Rendered 510976 of 786432 pixels (64%)
Rendered 512000 of 786432 pixels (65%)
Rendered 513024 of 786432 pixels (65%)
Rendered 514048 of 786432 pixels (65%)
Rendered 515072 of 786432 pixels (65%)
Rendered 516096 of 786432 pixels (65%)
Rendered 517120 of 786432 pixels (65%)
Rendered 518144 of 786432 pixels (65%)
Rendered 519168 of 786432 pixels (66%)
Rendered 520192 of 786432 pixels (66%)
Rendered 521216 of 786432 pixels (66%)
Rendered 522240 of 786432 pixels (66%)
Rendered 523264 of 786432 pixels (66%)
Rendered 524288 of 786432 pixels (66%)
Rendered 525312 of 786432 pixels (66%)
Rendered 526336 of 786432 pixels (66%)
Rendered 527360 of 786432 pixels (67%)
Rendered 528384 of 786432 pixels (67%)
Rendered 529408 of 786432 pixels (67%)
Rendered 530432 of 786432 pixels (67%)
Rendered 531456 of 786432 pixels (67%)
Rendered 532480 of 786432 pixels (67%)
==== [Paused] ==============================================================

Fatal error in renderer: Frontend halted render.
Render cancelled by user



In [2]:
print dagger.tt_log

[[ 0  0  0]
 [ 0  1  0]
 [ 0  2  0]
 [ 0  3  0]
 [ 0  4  0]
 [ 0  5  0]
 [ 0  6  0]
 [ 0  7  0]
 [ 0  8  0]
 [ 0  9  0]
 [ 0 10  0]
 [ 0 11  0]
 [ 0 12  0]
 [ 0 13  0]
 [ 0 14  0]
 [ 0 15  0]
 [ 0 16  0]
 [ 0 17  0]
 [ 0 18  0]
 [ 0 19  0]
 [ 0 20  0]
 [ 0 21  0]
 [ 0 22  0]
 [ 0 23  0]
 [ 0 24  0]
 [ 0 25  0]
 [ 0 26  0]
 [ 0 27  0]
 [ 0 28  0]
 [ 0 29  0]
 [ 0 30  0]
 [ 0 31  0]
 [ 0 32  0]
 [ 0 33  0]
 [ 0 34  0]
 [ 0 35  0]
 [ 0 36  0]
 [ 0 37  0]
 [ 0 38  0]
 [ 0 39  0]
 [ 0 40  0]
 [ 0 41  0]
 [ 0 42  0]
 [ 0 43  0]
 [ 0 44  0]
 [ 0 45  0]
 [ 0 46  0]
 [ 0 47  0]
 [ 0 48  0]
 [ 0 49  0]
 [ 0 50  0]
 [ 0 51  0]
 [ 0 52  0]
 [ 0 53  0]
 [ 0 54  0]
 [ 0 55  0]]
